spring:
  application:
    name: financas
  
  # Configurações do banco de dados
  datasource:
    url: jdbc:postgresql://100.124.125.39:5432/finance_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  
  # Configurações do JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Configurações do Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
